### ISSUE TITLE
Suggestion: Use Testcontainers `init-script` functionality to automatically run DB creation

### ISSUE THREAD

**Issue by GavinRay97** [sualeh/chinook-database#98]
Hello, thank for this work. I would like to offer a tip that I use in my project -- instead of using helper code to manually run `.sql` files for DB creation, you can copy the file into the container and have it automatically run to create the DB + rows:

```kt
// File is /src/test/resources/test-database-setup/init-mysql.sql
val mySQLContainer = MySQLContainer("mysql:8.0.28")
    .withInitScript("test-database-setup/init-mysql.sql")

// Oracle requires this workaround
val oracleContainer = OracleContainer("gvenzl/oracle-xe:21.3.0-slim")
    .withCopyFileToContainer(
        MountableFile.forClasspathResource("test-database-setup/init-oracle.sql"),
        "/container-entrypoint-startdb.d/init.sql"
    )

val postgresContainer = PostgreSQLContainer("postgres:14")
    .withInitScript("test-database-setup/init-postgres.sql")
```

I am not sure if this works with classpath files inside of a jar though, maybe you need `classpath://` as file URI or something?

**Comment by sualeh** [comment]
@GavinRay97 - thanks for the idea. 
1. The helper is very slyly providing coverage for [ChinookDatabaseUtils](https://github.com/sualeh/chinook-database/blob/master/src/main/java/us/fatehi/chinook_database/ChinookDatabaseUtils.java) also. 
2. It takes care of obtaining resources from the classpath. 
3. It is consistent for all the databases, including Oracle.

So I am not sure what value modifying the code in the mannger you suggest would have, since I would have to find ways to do these things listed above in some other way.
